{
 "title": "HPC Monitoring 2",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "GreenLab-STF : 145.108.225.7, GL5 : 145.108.225.16, GL6 : 145.108.225.17"
   }
  ]
 },
 "panels": [
  { "title": "${Node}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Node" },
  {
   "title": "CPU Utilization of Machine(%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"hpc_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"url\"] == \"http://${Node:value}:18080/metrics\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"scaph_process_cpu_usage_percentage\")\n  |> group(columns: [\"node\", \"_measurement\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "CPU Utilization per Process (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"hpc_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"url\"] == \"http://${Node:value}:18080/metrics\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"scaph_process_cpu_usage_percentage\")\n  |> filter(fn: (r) => exists r.cmdline and r.cmdline != \"\")\n  |> filter(fn: (r) => r._value != 0)\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> drop(columns: [\"url\", \"node\", \"host\", \"_field\"]) \n  |> yield(name: \"last\")\n"
    }
   ]
  },
  {
   "title": "Power Consumption Per Node (W)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"hpc_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"url\"] == \"http://${Node:value}:18080/metrics\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"scaph_host_power_microwatts\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000000.0 }))\n  |> drop(columns: [\"host\", \"url\", \"_field\"])\n  |> yield(name: \"mean\")\n"
    }
   ]
  },
  {
   "title": "Per Process Power Consumption (W)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 11 },
   "targets": [
    {
     "query": "from(bucket: \"hpc_monitoring\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"url\"] == \"http://${Node:value}:18080/metrics\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"scaph_process_power_consumption_microwatts\")\n  |> filter(fn: (r) => exists r.cmdline and r.cmdline != \"\")\n  |> filter(fn: (r) => r[\"_value\"] != 0)\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) / 1000000.0 }))\n  |> filter(fn: (r) => r._value != 0)\n  |> drop(columns: [\"url\", \"node\", \"host\", \"_field\"]) \n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}