services:
  # =================
  # Visualization
  # =================
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    networks:
      - monitoring-network
    ports:
      - "13000:3000"
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

volumes:
  grafana-volume:

networks:
  monitoring-network:
    driver: bridge
