global:
  resolve_timeout: 5m

route:
  receiver: 'slack'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: 'slack'
    slack_configs:
      - channel: '#servers'
        send_resolved: true
        username: 'Alertmanager'
        icon_emoji: ':warning:'
        title: '{{ .CommonAnnotations.summary }}'
        text: '{{ .CommonAnnotations.description }}'
        api_url: https://hooks.slack.com/services/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

