global:
  scrape_interval: 2s # If set lower than 2s, scaphandre energy readings will fail to be scraped
  scrape_timeout: 2s

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alert-manager:9093"]

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'scaphandre'
    static_configs:
      - targets: ['scaphandre:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8081']
