{
 "title": "Template Scaphandre",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasources", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "$Datasources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Datasources" },
  {
   "title": "Collector Component CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scaph_process_cpu_usage_percentage{exe=~\"/usr/bin/cadvisor|/usr/local/bin/scaphandre|/bin/node_exporter|/bin/prometheus\"}",
     "legendFormat": "{{exe}}"
    }
   ]
  },
  {
   "title": "Power Consumption (W)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scaph_host_power_microwatts / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scaph_process_cpu_usage_percentage)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Utilization (GB)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scaph_process_memory_bytes) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VRAM Utilization (GB)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(scaph_process_memory_virtual_bytes) / 1000000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "scaph_process_cpu_usage_percentage > 0",
     "legendFormat": "{{pid}} {{exe}}"
    }
   ]
  }
 ]
}