global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'scaphandre'
    static_configs:
      - targets: ['145.108.225.7:8080', '145.108.225.16:8080', '145.108.225.17:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8081']
