services:
  scaphandre:
    image: hubblo/scaphandre
    container_name: scaphandre
    restart: unless-stopped
    privileged: true
    expose:
      - "18080"
    command: 
      - "-s"
      - "powercap_rapl"
      - "prometheus"
    volumes:
      - type: bind
        source: /proc
        target: /proc
        bind:
          propagation: rshared

      - type: bind
        source: /sys/class/powercap
        target: /sys/class/powercap
        bind:
          propagation: rshared
    networks:
      - monitoring-network
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    expose:
      - "18081" # Only accessible within Docker network
    command:
      - "--port=8081"
      - "--store_container_labels=true"
      - "--global_housekeeping_interval=1m0s"
      - "--storage_duration=10s"

      # These optimizations lower CPU utilization of CAdvisor significantly (source: https://dev.to/cloudx/taming-cadvisors-high-cpu-usage-1nm5)
      - "--housekeeping_interval=1s"
      - "--docker_only=true" # This can be modified depending on necessity
      - "--disable_metrics=percpu,sched,tcp,udp,disk"
    networks:
      - monitoring-network
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /
        target: /rootfs
        read_only: true
      - type: bind
        source: /var/run
        target: /var/run
        read_only: true
      - type: bind
        source: /sys
        target: /sys
        read_only: true
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
        read_only: true


  node-exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    expose:
      - "19100" # Only accessible within Docker network
    restart: unless-stopped
    volumes:
      - type: bind
        source: /proc
        target: /host/proc
        read_only: true
        bind:
          propagation: rshared

      - type: bind
        source: /sys
        target: /host/sys
        read_only: true
        bind:
          propagation: rshared

      - type: bind
        source: /
        target: /rootfs
        read_only: true
        bind:
          propagation: rshared
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(diskstats|sys|proc|host|etc)($$|/)"
      # - '--collector.rapl' If Scaphandre is doing it, this is redundant
    networks:
      - monitoring-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # Make Prometheus accessible externally via localhost:9090
    expose:
      - "19090" # Only accessible within Docker network
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    # Configure retention to 2 weeks and store data in /prometheus
    command:
      - "--web.listen-address=:19090"
      - "--storage.tsdb.retention.time=2w"
      - "--storage.tsdb.path=/prometheus"
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring-network

  nginx:
    image: nginx:stable
    container_name: nginx-gateway
    ports:
      - "9090:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - prometheus
    networks:
      - monitoring-network

networks:
  monitoring-network:
    driver: bridge

volumes:
  prometheus_data:
