{
 "title": "System Performance",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Datasources", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "$Datasources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Datasources" },
  {
   "title": "Resource Utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(scaph_process_cpu_usage_percentage)",
     "legendFormat": "CPU"
    },
    {
     "expr": "sum(scaph_process_memory_bytes) / max(scaph_host_memory_total_bytes) * 100",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "scaph_host_cpu_frequency", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Power Consumption (W)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scaph_host_power_microwatts / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Collector Component CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "scaph_process_cpu_usage_percentage{exe=~\"/usr/bin/cadvisor|/usr/local/bin/scaphandre|/bin/node_exporter|/bin/prometheus\"}",
     "legendFormat": "{{exe}}"
    }
   ]
  },
  {
   "title": "Process Power Consumption (W)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "scaph_process_power_consumption_microwatts / 1000000 > 0",
     "legendFormat": "{{pid}} {{exe}}"
    }
   ]
  },
  {
   "title": "Process CPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "scaph_process_cpu_usage_percentage > 0",
     "legendFormat": "{{pid}} {{exe}}"
    }
   ]
  }
 ]
}